### ISSUE TITLE
Directionality index problem?

### ISSUE THREAD

**Issue by agalitsyna** [mikemoldovan/HiC_metrics#1]
Hi, I've learned about this repo from the Skotlech "Omics Data Analysis" Course. During your project at this course, it was presented as the "Python package" for the computation of multiple metrics for Hi-C data that can be used afterward (I did not find any documentation for this package, though). 
So, what is the function "direct_index" (non-documented, in [line 8 of metrica_lib.py](https://github.com/mikemoldovan/HiC_metrics/blob/master/metrica_lib.py#L8))?
How is it related to the Directionality Index, which is widely used for Hi-C data and introduced in [Dixon, 2012](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3356448/#!po=59.0909)?
The code does not seem to be related to the algorithm from the paper at all.

**Comment by mikemoldovan** [comment]
Thank you very much for pointing out the issue with the directionality index. That was indeed a non-finished function, for which the authors implore your forgiveness. Seems like now this issue is fixed.
Regarding documentation: should anyone ever be interested in our code, we would be happy to provide a detailed piece of documentation

**Comment by agalitsyna** [comment]
Cool, now it makes sense. Thanks!
